services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: YourStrongPassword
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - 1521:1521   # Oracle DB listener port
      - 5500:5500   # Oracle Enterprise Manager Express web console
    volumes:
      - oracle-data:/opt/oracle/oradata

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686  # Jaeger UI
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411  # Zipkin compatible endpoint

volumes:
  oracle-data:
    driver: local

#use this image instead: gvenzl/oracle-free!